---
title: "ENVS 193DS - Homework 3"
author: "Izzy Chang"
date: "2025-05-23"
format: html
---

## GitHub Repository:

<https://github.com/izzy-chang/ENVS-193DS_homework-03>

## Set Up

```{r}
#| message: false

# setting up packages
library(tidyverse)
library(here)
library(janitor)
library(readxl)
library(gt)
```

## Problem 1. Personal data

### a. Data summarizing

\[I could calculate the mean number of thesis hours I worked to compare average thesis productivity between days with above-median and below-median screen time, because I think I tend to procrastinate more on high screen time days, which may reduce the time I spend on my thesis. I could divide my screen time data into high vs low screen time groups by using the median screen time.\]

### b. Visualization

### c. Caption

### d. Table presentation

## Problem 2. Affective visualization

### a. Describe in words what an affective visualization could look like for your personal data

### b. Create a sketch (on paper) of your idea

### c. Make a draft of your visualization

### d. Write an artist statement

## Problem 3. Statistical critique

### a. Revisit and summarize

### b. Visual clarity

### c. Aesthetic clarity

### d. Recommendations

```         
```

```         
```
